# Generated by Django 3.2.5 on 2021-07-23 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('char2', models.CharField(max_length=2)),
                ('char30', models.CharField(max_length=30)),
                ('auto_counter', models.AutoField(primary_key=True, serialize=False)),
                ('bin_f', models.BinaryField()),
                ('is_test', models.BooleanField()),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
                ('time', models.TimeField()),
                ('dec53', models.DecimalField(decimal_places=3, max_digits=5)),
                ('dec33', models.DecimalField(decimal_places=3, max_digits=3)),
                ('duration', models.DurationField()),
                ('email', models.EmailField(max_length=254)),
                ('file', models.FileField(upload_to='')),
                ('floating', models.FloatField()),
                ('img', models.ImageField(upload_to='')),
                ('json', models.JSONField()),
                ('n_bool2', models.BooleanField(null=True)),
                ('slug', models.SlugField()),
                ('url_d', models.URLField()),
                ('uuid', models.UUIDField()),
                ('choices', models.ManyToManyField(to='polls.Choice')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
